// Generated by CoffeeScript 1.4.0
(function() {
  var open_dialog, open_new_tab;

  open_dialog = function(dialogue, element) {
    dialogue.dialog("option", {
      position: {
        my: "center bottom",
        at: "center top",
        of: element
      }
    });
    return dialogue.dialog("open");
  };

  open_new_tab = function(url) {
    return window.open(url, '_self').focus();
  };

  $(function() {
    $(".dialog").dialog({
      autoOpen: false,
      dialogClass: "noTitleStuff",
      height: "auto",
      width: "auto",
      autoResize: true
    });
    return $.get("img/carte4.svg", function(rawSvg) {
      var anchor;
      $("#map").append(document.importNode(rawSvg.documentElement, true));
      anchor = "#crocodile, #poisson1, #poisson2, #tribunal, #text3913, #text4897, #text4901, #text4905, #text3775, #text3785, #text3779";
      $(anchor).on("mouseenter", function() {
        return $(this).css('cursor', 'pointer');
      });
      $(anchor).on("mouseleave", function() {
        return $(this).css('cursor', 'default');
      });
      $("#text3913").on("click", function() {
        return open_new_tab("sophus.html");
      });
      $("#poisson1, #poisson2, #text4897, #text3779").on("click", function() {
        return open_new_tab("Carroll/tag3.html");
      });
      $("#crocodile, #text4901, #text3775").on("click", function() {
        return open_new_tab("AlligatorEggs/index.html");
      });
      return $("#tribunal, #text4905, #text3785").on("click", function() {
        return open_new_tab("Carroll/LogicGame5.html");
      });
    }, "xml");
  });

}).call(this);
