// Generated by CoffeeScript 1.9.0
(function() {
  var open_dialog, open_new_tab;

  open_dialog = function(dialogue, element) {
    dialogue.dialog("option", {
      position: {
        my: "center bottom",
        at: "center top",
        of: element
      }
    });
    return dialogue.dialog("open");
  };

  open_new_tab = function(url) {
    return window.open(url, '_self').focus();
  };

  $(function() {
    $(".dialog").dialog({
      autoOpen: false,
      dialogClass: "noTitleStuff",
      height: "auto",
      width: "auto",
      autoResize: true
    });
    return $.get("img/carte2.svg", function(rawSvg) {
      var anchor;
      $("#map").append(document.importNode(rawSvg.documentElement, true));
      anchor = "#crocodile, #poisson1, #poisson2, #tribunal, #tspan3925, #tspan3927, #tspan3929";
      $(anchor).on("mouseenter", function() {
        return $(this).css('cursor', 'pointer');
      });
      $(anchor).on("mouseleave", function() {
        return $(this).css('cursor', 'default');
      });
      $("#crocodile, #tspan3927").on("click", function() {
        return open_new_tab("AlligatorEggs/index.html");
      });
      $("#poisson1, #poisson2, #tspan3925").on("click", function() {
        return open_new_tab("Carroll/tag3.html");
      });
      return $("#tribunal, #tspan3929").on("click", function() {
        return open_new_tab("Carroll/LogicGame1.html");
      });
    }, "xml");
  });

}).call(this);
